In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,10,(2,1,2))
b=np.random.randint(1,10,(1,2,1))

In [3]:
a

array([[[8, 3]],

       [[2, 1]]])

In [4]:
b

array([[[2],
        [9]]])

In [6]:
a+b#broadcasting

array([[[10,  5],
        [17, 12]],

       [[ 4,  3],
        [11, 10]]])