In [1]:
import numpy as np

In [3]:
k=np.zeros(shape=(3,3))
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
k.shape , k.size ,k.ndim

((3, 3), 9, 2)

In [12]:
b=np.ones(shape=(10))
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
b.shape , b.size ,b.ndim

((10,), 10, 1)

In [13]:
np.full(shape=(3,3),fill_value=4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
np.random.rand(2,2)

array([[0.24651648, 0.45607228],
       [0.40323934, 0.66774342]])

In [22]:
np.random.randint(1,10,(2,2))

array([[2, 6],
       [2, 4]])

In [24]:
np.linspace(1,10,4,retstep=True)

(array([ 1.,  4.,  7., 10.]), 3.0)