# Fancy indexing

In [9]:
import numpy as np

In [10]:
a=np.random.randint(1,10,5)

In [11]:
a

array([4, 4, 8, 2, 5])

In [12]:
a[[0,3,2]]

array([4, 2, 8])

# Boolean Indexing

In [13]:
a[[True,False,True,False,False]]

array([4, 8])

# Vectorization Operations

In [14]:
a%2==0

array([ True,  True,  True,  True, False])

In [15]:
a[a%2==0]

array([4, 4, 8, 2])

## Masking

In [16]:
nos_greater_than_5=a>5

In [17]:
a[nos_greater_than_5]

array([8])

In [19]:
a.sum(axis=0)

23