In [22]:
import numpy as np

In [23]:
a=np.arange(1,11)
a
a.shape

(10,)

In [24]:
a[::-2]

array([10,  8,  6,  4,  2])

In [25]:
a[4:7]

array([5, 6, 7])

In [26]:
a[-3:-1]

array([8, 9])

In [27]:
print(type(range(1,10)))
for n in range(1,10):
    print(n)
print(type(np.array([10,20])))

<class 'range'>
1
2
3
4
5
6
7
8
9
<class 'numpy.ndarray'>


In [28]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
a[2,2]

13

In [30]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
a[-2:,-5:-3]

array([[16, 17],
       [21, 22]])

In [ ]:
x