# Stacking

In [1]:
import numpy as np

In [2]:
a=np.arange(4).reshape(2,2)
b=np.arange(20,24).reshape(2,2)

In [3]:
a

array([[0, 1],
       [2, 3]])

In [4]:
b

array([[20, 21],
       [22, 23]])

In [6]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [20, 21],
       [22, 23]])

In [7]:
np.hstack((a,b))

array([[ 0,  1, 20, 21],
       [ 2,  3, 22, 23]])

# Splitting

In [21]:
a= np.arange(1,11)

In [24]:
a1,a2=np.hsplit(a,2)

In [25]:
a1

array([1, 2, 3, 4, 5])

In [26]:
a2

array([ 6,  7,  8,  9, 10])

In [27]:
a1,a2,a3=np.hsplit(a,(2,3))

In [28]:
print(a1)
print(a2)
print(a3)


[1 2]
[3]
[ 4  5  6  7  8  9 10]


In [32]:
k=a1.reshape(2,1)

In [34]:
k.ravel()#view

array([1, 2])

In [35]:
k.flatten()#copy

array([1, 2])

In [38]:
k.T

array([[1, 2]])

In [43]:
k.resize(2,1)# does inplace change returns no view/copy unlike reshape which returns view

In [44]:
k

array([[1],
       [2]])

In [49]:
import numpy as np
arr = np.array([[1, 2, 3],
                [6, 7, 8]])
print (np.max(arr, axis = 1))

[3 8]


In [50]:
a=np.arange(10).reshape(5,2)

In [51]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
b=a.T

In [58]:
b[0,0]=1000
b

array([[1000,    2,    4,    6,    8],
       [   1,    3,    5,    7,    9]])

In [59]:
a

array([[1000,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9]])