# View works on actual array's reference 

In [1]:
import numpy as np

In [2]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b=a[:5]
b

array([0, 1, 2, 3, 4])

In [5]:
b[0]=7

In [6]:
a

array([7, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# copy

In [7]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [9]:
b=a.copy()
b

array([0, 1, 2, 3, 4, 5])

In [10]:
b[0]=1000

In [12]:
b


array([1000,    1,    2,    3,    4,    5])

In [13]:
a

array([0, 1, 2, 3, 4, 5])

In [14]:
c=a.view()

In [16]:
c[0]=1003

In [17]:
c

array([1003,    1,    2,    3,    4,    5])

In [18]:
a

array([1003,    1,    2,    3,    4,    5])

view results from slice,split,reshape,ravel

copy result from stacking,flatten